repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
    - id: ruff
      args: [ --fix ]
      exclude: meetup_files
    - id: ruff-format
      exclude: meetup_files
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  exclude: meetup_files
  hooks:
  - id: mypy
    name: Run MyPy typing checks.
    args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
    exclude: meetup_files
