# Generated by Django 5.1.5 on 2025-02-23 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "people"},
        ),
        migrations.RemoveField(
            model_name="event",
            name="presentations",
        ),
        migrations.AddField(
            model_name="presentation",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentations",
                to="main.event",
            ),
            preserve_default=False,
        ),
    ]
