# Generated by Django 5.1.5 on 2025-03-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_presentation_options_presentation_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date_time"]},
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
