# Generated by Django 5.1.5 on 2025-03-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_event_options_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
