# Generated by Django 5.1.5 on 2025-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_event_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="meetup_com_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
