# Generated by Django 5.1.5 on 2025-03-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_event_meetup_com_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["name"], "verbose_name_plural": "people"},
        ),
        migrations.AddField(
            model_name="person",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
