# Generated by Django 5.1.5 on 2025-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_person_options_person_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
