# Generated by Django 5.1.5 on 2025-03-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_person_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
