# Generated by Django 5.1.5 on 2025-03-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
